[aws]
format = 'on [$symbol($profile )(\($region\) )]($style)'
style = "bold blue"
symbol = "ðŸ…° "
[aws.region_aliases]
ap-southeast-2 = "au"
us-east-1 = "va"

[nodejs]
format = " [ï¢˜  $version](bold green) "

[character]
success_symbol = "[â››](bold green) "
error_symbol = "[â››](bold red) "
